import type { ReactNode } from "react";

/** Who authored a chat message. */
export type ChatRole = "user" | "assistant" | "system" | "tool";

/** Lifecycle of a single chat message. */
export type MessageStatus = "queued" | "streaming" | "complete" | "error";

/** Lifecycle of an agent / workflow run. */
export type RunStatus =
  | "idle"
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "canceled"
  | "paused";

/** Lifecycle of a single tool invocation. */
export type ToolCallStatus = "pending" | "running" | "success" | "error";

/** Thumbs feedback on an assistant response. */
export type FeedbackValue = "up" | "down";

/** Token accounting for a conversation or request. */
export interface TokenUsage {
  /** Tokens consumed by the prompt / context. */
  prompt: number;
  /** Tokens generated by the model. */
  completion: number;
  /** Context-window or budget limit, when known. */
  limit?: number;
}

/** A selectable model in a model picker. */
export interface ModelOption {
  id: string;
  name: string;
  /** Provider key — e.g. "openai", "anthropic", "google", "meta", "mistral", "cloudflare". */
  provider?: string;
  /** Context window in tokens (e.g. 200_000). */
  contextWindow?: number;
  /** Short marketing tag, e.g. "New" or "Fastest". */
  tag?: string;
  description?: string;
}

/** A tool / function invocation made by a model. */
export interface ToolCall {
  id: string;
  /** Tool name, e.g. "search_documents". */
  name: string;
  status: ToolCallStatus;
  /** Arguments the model called the tool with (rendered as JSON). */
  args?: unknown;
  /** Result payload (string is rendered as text, objects as JSON). */
  result?: unknown;
  /** Human summary shown next to the name while collapsed. */
  description?: string;
  durationMs?: number;
  /** Error message when status is "error". */
  error?: string;
}

/** A retrieval / citation source attached to a response. */
export interface SourceRef {
  id: string;
  title: string;
  url?: string;
  /** Snippet shown in the hover tooltip. */
  snippet?: string;
}

/** Summary of an agent for cards and lists. */
export interface AgentSummary {
  id: string;
  name: string;
  description?: string;
  status?: RunStatus;
  /** Model id/name the agent runs on, e.g. "claude-4.5-opus". */
  model?: string;
  tags?: string[];
  /** Custom icon node for the agent tile. */
  icon?: ReactNode;
}
